---------------------------------------------------------------------------------
--! @file register_pack.vhd
--!
--! @brief  register_types package
--! @author Tobias Stark (tobias.stark@dfki.de)
--! @date   29.10.2014
--!
--! This package provides some types to work with the registers.\n
--! This file will also be used by the RobotConfig c++ library in the
--! autogenerated vhd-files.\n\n
--! German Research Center for Artificial Intelligence\n
--!
--! $LastChangedRevision: 3595 $
--! $LastChangedBy: tstark $
--! $LastChangedDate: 2014-10-29 13:52:34 +0100 (Wed, 29 Oct 2014) $
---------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

package register_types is

    -- type for the register types (see also: c++ library representations 'Register.h')
    type registertype_t is (UINT8, INT8, UINT16, INT16, SINGLEFLOAT, UINT32, INT32, DOUBLEFLOAT, UINT64, INT64, ERROR);

    -- type for the register memory types
    type reg_mem_type_t is (RAM, PROM, RO, ERROR);

    -- type for the register memory arrays where the register data is stored
    type reg_mem_array_t is array (Natural range <>) of std_logic_vector(7 downto 0);
    
    -- types for register mapping
    type reg_types_t     is array (natural range <>) of registertype_t;
    type reg_mem_types_t is array (natural range <>) of reg_mem_type_t;
    type reg_mem_map_t   is array (natural range <>) of natural;

end package register_types;
